// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using harbour.helpers;

namespace api.Migrations
{
    [DbContext(typeof(HarbourDb))]
    [Migration("20210420202228_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("harbour.models.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Speedboat",
                            Speed = "30"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sailboat",
                            Speed = "15"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cargo ship",
                            Speed = "5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
