// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using harbour.helpers;

namespace api.Migrations
{
    [DbContext(typeof(HarbourDb))]
    [Migration("20210421170809_name")]
    partial class name
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("harbour.models.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Boat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Speedboat",
                            Speed = 30
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sailboat",
                            Speed = 15
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cargo ship",
                            Speed = 5
                        });
                });

            modelBuilder.Entity("harbour.models.BoatTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<TimeSpan>("ArrivalTimeAtHarbour")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ArrivalTimeAtOpenSea")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DepartureTimeAtOpenSea")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BoatTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
